name: Build and Push Docker Image

permissions:
  contents: read
  packages: write

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repository
        run: |
          echo "IMAGE_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

      - name: Get release tag
        id: get_release_tag
        run: |
          echo "TAG=${GITHUB_REF##*/}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --push \
            .

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io
